site_name: "InScane SMP"
site_description: "Official documentation for the InScane SMP Server and available commands."
site_author: "Ashton Miller"
site_url: "https://vernandogames.github.io/InScane-SMP"
theme:
  name: 'material'
  lang: 'en'
  favicon: 'images/icon.png'
  palette: 
    scheme: preference

extra: 
  manifest: 'manifest.webmanifest'

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized

# Register the service worker
extra_javascript:
#  - 'javascripts/sw-src.js'
  - 'assets/javascripts/rsw.js'

#PWA Config
use_directory_urls: false
scope: "./"
version: 1.0.2